/* Generated by agamc — Agam Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <time.h>

typedef int64_t agam_int;
typedef double agam_float;
typedef int agam_bool;
typedef const char* agam_str;

/* ── Agam Runtime Prelude ──────────────────── */
agam_int agam_println(agam_str s) { printf("%s\n", s); return 0; }
agam_int agam_print(agam_str s) { printf("%s", s); return 0; }
double agam_clock() { return (double)clock() / CLOCKS_PER_SEC; }

/* ── External function stubs ── */
agam_int agam_next(agam_int __a0);
agam_int agam_len(agam_int __a0);
agam_int agam_has_next(agam_int __a0);

int main(int argc, char** argv);

int main(int argc, char** argv) {
block_0:
  agam_int _local_name = 0;
  agam_int __v0 = 0;
  agam_str __v1 = "World";
  _local_name = __v1;
  agam_int __v2 = __v1;
  agam_str __v3 = "Hello, ";
  agam_int __v4 = _local_name;
  agam_int __v5 = __v3 + __v4;
  agam_str __v6 = "!";
  agam_int __v7 = __v5 + __v6;
  printf("%lld", (long long)__v7);
  printf("\n");
  agam_int __v8 = 0;
  agam_int _local_scores = 0;
  agam_int __v9 = 0;
  agam_int __v10 = 90;
  agam_int __v11 = 85;
  agam_int __v12 = 72;
  agam_int __v13 = 95;
  agam_int __v14 = 0; /* unit */
  _local_scores = __v14;
  agam_int __v15 = __v14;
  agam_int _local_total = 0;
  agam_int __v16 = 0;
  agam_int __v17 = 0;
  _local_total = __v17;
  agam_int __v18 = __v17;
  goto block_1;
block_1:
  agam_int __v19 = _local___iter_14;
  agam_int __v20 = agam_has_next(__v19);
  if (__v20) goto block_2; else goto block_3;
block_2:
  agam_int _local_score = 0;
  agam_int __v21 = 0;
  agam_int __v22 = _local___iter_14;
  agam_int __v23 = agam_next(__v22);
  _local_score = __v23;
  agam_int __v24 = __v23;
  agam_int __v25 = _local_total;
  agam_int __v26 = _local_score;
  agam_int __v27 = __v25 + __v26;
  _local_total = __v27;
  agam_int __v28 = __v27;
  goto block_1;
block_3:
  agam_int _local_avg = 0;
  agam_int __v29 = 0;
  agam_int __v30 = _local_total;
  agam_int __v31 = _local_scores;
  agam_int __v32 = agam_len(__v31);
  agam_int __v33 = __v30 / __v32;
  _local_avg = __v33;
  agam_int __v34 = __v33;
  agam_str __v35 = "Average score: {}";
  agam_int __v36 = _local_avg;
  printf("%lld", (long long)__v35);
  printf(" ");
  printf("%lld", (long long)__v36);
  printf("\n");
  agam_int __v37 = 0;
  agam_int __v38 = 0;
  return (int)__v38;
block_4:
  agam_int __v39 = 0; /* unit */
  return (int)__v39;
}

