//! C code emitter — translates MIR into C source code.
//!
//! The generated C code can be compiled with any standard C compiler
//! to produce native binaries. This is the simplest path to running
//! Agam programs natively without requiring LLVM bindings.

use std::fmt::Write;
use agam_mir::ir::*;

/// Emit a complete MIR module as C source code.
pub fn emit_c(module: &MirModule) -> String {
    let mut output = String::new();

    // Header
    writeln!(output, "/* Generated by agamc — Agam Compiler */").unwrap();
    writeln!(output, "#include <stdio.h>").unwrap();
    writeln!(output, "#include <stdlib.h>").unwrap();
    writeln!(output, "#include <string.h>").unwrap();
    writeln!(output, "#include <stdint.h>").unwrap();
    writeln!(output, "#include <math.h>").unwrap();
    writeln!(output, "#include <time.h>").unwrap();
    writeln!(output).unwrap();

    // Type aliases
    writeln!(output, "typedef int64_t agam_int;").unwrap();
    writeln!(output, "typedef double agam_float;").unwrap();
    writeln!(output, "typedef int agam_bool;").unwrap();
    writeln!(output, "typedef const char* agam_str;").unwrap();
    writeln!(output).unwrap();

    // Runtime prelude — stub implementations for standard library functions
    writeln!(output, "/* ── Agam Runtime Prelude ──────────────────── */").unwrap();
    writeln!(output, "agam_int agam_println(agam_str s) {{ printf(\"%s\\n\", s); return 0; }}").unwrap();
    writeln!(output, "agam_int agam_print(agam_str s) {{ printf(\"%s\", s); return 0; }}").unwrap();
    writeln!(output, "double agam_clock() {{ return (double)clock() / CLOCKS_PER_SEC; }}").unwrap();
    writeln!(output).unwrap();

    // Collect all unknown function calls and generate stub declarations
    let mut unknown_funcs: std::collections::HashSet<String> = std::collections::HashSet::new();
    for func in &module.functions {
        for block in &func.blocks {
            for instr in &block.instructions {
                if let Op::Call { callee, args } = &instr.op {
                    let mangled = mangle_name(callee);
                    if callee != "print" && callee != "println"
                        && !module.functions.iter().any(|f| mangle_name(&f.name) == mangled)
                        && mangled != "agam_println" && mangled != "agam_print"
                        && mangled != "agam_clock"
                    {
                        unknown_funcs.insert(format!("agam_int {}({});",
                            mangled,
                            (0..args.len()).map(|i| format!("agam_int __a{}", i)).collect::<Vec<_>>().join(", ")
                        ));
                    }
                }
            }
        }
    }
    if !unknown_funcs.is_empty() {
        writeln!(output, "/* ── External function stubs ── */").unwrap();
        for stub in &unknown_funcs {
            writeln!(output, "{}", stub).unwrap();
        }
        writeln!(output).unwrap();
    }

    // Forward declarations
    for func in &module.functions {
        if func.name == "main" {
            writeln!(output, "int main(int argc, char** argv);").unwrap();
        } else {
            write!(output, "agam_int {}(", mangle_name(&func.name)).unwrap();
            for (i, _) in func.params.iter().enumerate() {
                if i > 0 { write!(output, ", ").unwrap(); }
                write!(output, "agam_int __p{}", i).unwrap();
            }
            writeln!(output, ");").unwrap();
        }
    }
    writeln!(output).unwrap();

    // Function definitions
    for func in &module.functions {
        emit_function(&mut output, func);
        writeln!(output).unwrap();
    }

    output
}

fn emit_function(out: &mut String, func: &MirFunction) {
    // Function signature
    if func.name == "main" {
        writeln!(out, "int main(int argc, char** argv) {{").unwrap();
    } else {
        write!(out, "agam_int {}(", mangle_name(&func.name)).unwrap();
        for (i, _param) in func.params.iter().enumerate() {
            if i > 0 { write!(out, ", ").unwrap(); }
            write!(out, "agam_int __p{}", i).unwrap();
        }
        writeln!(out, ") {{").unwrap();
    }

    // Emit parameter → local aliases
    for (i, param) in func.params.iter().enumerate() {
        writeln!(out, "  agam_int {} = __p{};", mangle_local(&param.name), i).unwrap();
    }

    // Emit all basic blocks
    for block in &func.blocks {
        emit_block(out, block);
    }

    writeln!(out, "}}").unwrap();
}

fn emit_block(out: &mut String, block: &BasicBlock) {
    writeln!(out, "block_{}:", block.id.0).unwrap();

    for instr in &block.instructions {
        emit_instruction(out, instr);
    }

    emit_terminator(out, &block.terminator);
}

fn emit_instruction(out: &mut String, instr: &Instruction) {
    let v = format!("__v{}", instr.result.0);

    match &instr.op {
        Op::ConstInt(val) => {
            writeln!(out, "  agam_int {} = {};", v, val).unwrap();
        }
        Op::ConstFloat(val) => {
            writeln!(out, "  agam_float {} = {};", v, val).unwrap();
        }
        Op::ConstBool(val) => {
            writeln!(out, "  agam_bool {} = {};", v, if *val { 1 } else { 0 }).unwrap();
        }
        Op::ConstString(val) => {
            writeln!(out, "  agam_str {} = \"{}\";", v, escape_c_string(val)).unwrap();
        }
        Op::Unit => {
            writeln!(out, "  agam_int {} = 0; /* unit */", v).unwrap();
        }
        Op::BinOp { op, left, right } => {
            let op_str = binop_to_c(*op);
            writeln!(out, "  agam_int {} = __v{} {} __v{};", v, left.0, op_str, right.0).unwrap();
        }
        Op::UnOp { op, operand } => {
            let op_str = unop_to_c(*op);
            writeln!(out, "  agam_int {} = {}__v{};", v, op_str, operand.0).unwrap();
        }
        Op::Call { callee, args } => {
            if callee == "print" || callee == "println" || callee == "print_int" || callee == "print_str" {
                let is_str = callee == "print_str";
                if args.is_empty() {
                    writeln!(out, "  printf(\"\\n\");").unwrap();
                } else {
                    for (i, arg) in args.iter().enumerate() {
                        if i > 0 {
                            writeln!(out, "  printf(\" \");").unwrap();
                        }
                        if is_str {
                            writeln!(out, "  printf(\"%s\", (agam_str)__v{});", arg.0).unwrap();
                        } else {
                            writeln!(out, "  printf(\"%lld\", (long long)__v{});", arg.0).unwrap();
                        }
                    }
                    if callee == "println" || callee == "print_str" {
                        writeln!(out, "  printf(\"\\n\");").unwrap();
                    } else if callee == "print" || callee == "print_int" {
                        writeln!(out, "  printf(\"\\n\");").unwrap(); // always append newline for benchmarking clarify
                    }
                }
                writeln!(out, "  agam_int {} = 0;", v).unwrap();
            } else {
                let arg_strs: Vec<String> = args.iter().map(|a| format!("__v{}", a.0)).collect();
                writeln!(out, "  agam_int {} = {}({});", v, mangle_name(callee), arg_strs.join(", ")).unwrap();
            }
        }
        Op::Copy(value) => {
            writeln!(out, "  agam_int {} = __v{};", v, value.0).unwrap();
        }
        Op::LoadLocal(name) => {
            writeln!(out, "  agam_int {} = {};", v, mangle_local(name)).unwrap();
        }
        Op::StoreLocal { name, value } => {
            writeln!(out, "  {} = __v{};", mangle_local(name), value.0).unwrap();
            writeln!(out, "  agam_int {} = __v{};", v, value.0).unwrap();
        }
        Op::Alloca { name, .. } => {
            writeln!(out, "  agam_int {} = 0;", mangle_local(name)).unwrap();
            writeln!(out, "  agam_int {} = 0;", v).unwrap();
        }
        Op::GetField { object, field } => {
            writeln!(out, "  agam_int {} = __v{}; /* .{} */", v, object.0, field).unwrap();
        }
        Op::GetIndex { object, index } => {
            writeln!(out, "  agam_int {} = __v{}; /* [__v{}] */", v, object.0, index.0).unwrap();
        }
        Op::Phi(entries) => {
            writeln!(out, "  agam_int {} = 0; /* phi */", v).unwrap();
            for (block, val) in entries {
                writeln!(out, "  /* phi: block_{} -> __v{} */", block.0, val.0).unwrap();
            }
        }
        Op::Cast { value, .. } => {
            writeln!(out, "  agam_int {} = (agam_int)__v{};", v, value.0).unwrap();
        }
    }
}

fn emit_terminator(out: &mut String, term: &Terminator) {
    match term {
        Terminator::Return(val) => {
            writeln!(out, "  return (int)__v{};", val.0).unwrap();
        }
        Terminator::ReturnVoid => {
            writeln!(out, "  return 0;").unwrap();
        }
        Terminator::Jump(block) => {
            writeln!(out, "  goto block_{};", block.0).unwrap();
        }
        Terminator::Branch { condition, then_block, else_block } => {
            writeln!(out, "  if (__v{}) goto block_{}; else goto block_{};",
                condition.0, then_block.0, else_block.0).unwrap();
        }
        Terminator::Unreachable => {
            writeln!(out, "  __builtin_unreachable();").unwrap();
        }
    }
}

fn binop_to_c(op: MirBinOp) -> &'static str {
    match op {
        MirBinOp::Add => "+",
        MirBinOp::Sub => "-",
        MirBinOp::Mul => "*",
        MirBinOp::Div => "/",
        MirBinOp::Mod => "%",
        MirBinOp::Eq => "==",
        MirBinOp::NotEq => "!=",
        MirBinOp::Lt => "<",
        MirBinOp::LtEq => "<=",
        MirBinOp::Gt => ">",
        MirBinOp::GtEq => ">=",
        MirBinOp::And => "&&",
        MirBinOp::Or => "||",
        MirBinOp::BitAnd => "&",
        MirBinOp::BitOr => "|",
        MirBinOp::BitXor => "^",
        MirBinOp::Shl => "<<",
        MirBinOp::Shr => ">>",
    }
}

fn unop_to_c(op: MirUnOp) -> &'static str {
    match op {
        MirUnOp::Neg => "-",
        MirUnOp::Not => "!",
        MirUnOp::BitNot => "~",
    }
}

fn mangle_name(name: &str) -> String {
    format!("agam_{}", name.replace("::", "_").replace(".", "_"))
}

fn mangle_local(name: &str) -> String {
    format!("_local_{}", name.replace("::", "_").replace(".", "_"))
}

fn escape_c_string(s: &str) -> String {
    s.replace('\\', "\\\\")
     .replace('"', "\\\"")
     .replace('\n', "\\n")
     .replace('\t', "\\t")
}

#[cfg(test)]
mod tests {
    use super::*;
    use agam_hir::lower::HirLowering;
    use agam_mir::lower::MirLowering;
    use agam_lexer::Lexer;
    use agam_errors::span::SourceId;

    fn compile_to_c(source: &str) -> String {
        let source_id = SourceId(0);
        let mut lexer = Lexer::new(source, source_id);
        let mut tokens = Vec::new();
        loop {
            let tok = lexer.next_token();
            let is_eof = tok.kind == agam_lexer::TokenKind::Eof;
            tokens.push(tok);
            if is_eof { break; }
        }
        let mut parser = agam_parser::Parser::new(tokens);
        let module = parser.parse_module(source_id).expect("parse failed");

        let mut hir_lower = HirLowering::new();
        let hir = hir_lower.lower_module(&module);

        let mut mir_lower = MirLowering::new();
        let mir = mir_lower.lower_module(&hir);

        emit_c(&mir)
    }

    #[test]
    fn test_emit_main_function() {
        let c = compile_to_c("fn main(): return 42");
        assert!(c.contains("int main("), "C output should have main function");
        assert!(c.contains("42"), "C output should have the literal 42");
        assert!(c.contains("return"), "C output should have return");
    }

    #[test]
    fn test_emit_includes() {
        let c = compile_to_c("fn main(): return 0");
        assert!(c.contains("#include <stdio.h>"));
        assert!(c.contains("#include <stdint.h>"));
    }

    #[test]
    fn test_emit_binary_op() {
        let c = compile_to_c("fn main(): let x = 1 + 2");
        assert!(c.contains("+"), "C output should contain addition");
    }

    #[test]
    fn test_emit_print_call() {
        let c = compile_to_c("fn main(): print(42)");
        assert!(c.contains("printf"), "C output should emit printf for print()");
    }

    #[test]
    fn test_emit_type_aliases() {
        let c = compile_to_c("fn main(): return 0");
        assert!(c.contains("typedef int64_t agam_int;"));
        assert!(c.contains("typedef double agam_float;"));
    }

    #[test]
    fn test_full_pipeline() {
        let c = compile_to_c("fn main(): let x = 10 + 20");
        // Should produce valid-looking C code
        assert!(c.contains("int main("));
        assert!(c.contains("_local_x"));
        assert!(c.contains("return"));
    }
}
