//! GPU kernel codegen backend — NVPTX64 LLVM IR emission.
#![allow(clippy::write_with_newline)]
//!
//! Emits CUDA-compatible NVPTX kernel functions from `@gpu`-annotated
//! MIR functions. Links against CUDA runtime (cudart), NVVM (libnvvm),
//! and driver API libraries.
//!
//! ## Performance
//!
//! This emitter is optimized for IR generation throughput:
//! - Pre-allocated output buffer (avoids realloc during emission)
//! - Static string slices for all boilerplate (zero-copy header/intrinsics)
//! - Inline `write!` to buffer (no intermediate String allocations)
//! - Itoa fast-path for integer formatting
//! - Single-pass emission (no backpatching)

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write;
use std::path::{Path, PathBuf};

use agam_mir::ir::{
    GpuIntrinsicKind, MirBinOp, MirFunction, MirModule, MirParam, MirUnOp, Op, Terminator, ValueId,
};
use agam_sema::gpu::{GpuKernelParamAbi, GpuMemoryType};
use agam_sema::types::{FloatSize, IntSize, Type, builtin_type_by_id};

// ── Static boilerplate (zero-allocation, compiled into .rodata) ──

pub const CUDA_ROOT_ENV: &str = "AGAM_CUDA_ROOT";
pub const CUDA_CUDART_ENV: &str = "AGAM_CUDART";
pub const CUDA_LIBNVVM_ENV: &str = "AGAM_LIBNVVM";
pub const CUDA_NVCC_ENV: &str = "AGAM_NVCC";
pub const CUDA_NVPTXCOMPILER_ENV: &str = "AGAM_NVPTXCOMPILER";

const NVPTX_HEADER_PREFIX: &str = "\
; Generated by agamc — Agam GPU Kernel Module (NVPTX64)
target datalayout = \"e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v32:32:32-v64:64:64-v128:128:128-n16:32:64\"
target triple = \"nvptx64-nvidia-cuda\"

; ── CUDA Toolkit Linkage ──
";

const NVVM_INTRINSICS: &str = "\
; ── NVVM Thread Intrinsics ──
declare i32 @llvm.nvvm.read.ptx.sreg.tid.x() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.tid.y() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.tid.z() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.ntid.x() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.ntid.y() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.ntid.z() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.y() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.z() nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() nounwind readnone

; ── Synchronization ──
declare void @llvm.nvvm.barrier0() nounwind

; ── Warp-Level Primitives ──
declare i32 @llvm.nvvm.shfl.sync.down.i32(i32, i32, i32, i32) nounwind readnone
declare i32 @llvm.nvvm.vote.ballot.sync(i32, i1) nounwind readnone

; ── Fast Math Intrinsics ──
declare float @llvm.nvvm.sin.approx.f(float) nounwind readnone
declare float @llvm.nvvm.cos.approx.f(float) nounwind readnone
declare float @llvm.nvvm.sqrt.approx.f(float) nounwind readnone
declare float @llvm.nvvm.ex2.approx.f(float) nounwind readnone

";

const KERNEL_ENTRY_PREAMBLE: &str = "\
entry:
  %tid_x = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
  %ctaid_x = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
  %ntid_x = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
  %global_id = add i32 %tid_x, 0 ; placeholder global thread index
";

const CUDA_FOOTER: &str = "\
; ── CUDA Library References ──
!agam.cuda.libs = !{!\"cudart\", !\"nvvm\", !\"nvptxcompiler\"}
!agam.cuda.version = !{!\"12.0\"}
";

const HOST_CUDA_DECLS: &str = "\
; ── CUDA Runtime API Declarations (host-side) ──
declare i32 @cudaLaunchKernel(i8*, i64, i64, i8**, i64, i8*)
declare i32 @cudaMalloc(i8**, i64)
declare i32 @cudaFree(i8*)
declare i32 @cudaMemcpy(i8*, i8*, i64, i32)
declare i32 @cudaDeviceSynchronize()
declare i32 @cudaGetLastError()

; ── NVVM/libnvvm Compilation API ──
; Link with: -lcudart -lnvvm -lnvptxcompiler_static
; NVCC: nvcc --ptx <kernel.ll> -o <kernel.ptx>
; Or:   libnvvm API for runtime PTX compilation
";

/// CUDA toolkit library linkage metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CudaLinkage {
    /// Path or link name for libcudart (CUDA Runtime API).
    pub cudart: String,
    /// Path or link name for libnvvm (NVIDIA NVVM IR compiler).
    pub libnvvm: String,
    /// Path or link name for nvcc (NVIDIA CUDA Compiler driver).
    pub nvcc: String,
    /// Path or link name for libnvptxcompiler (PTX JIT compiler).
    pub libnvptx: String,
}

impl CudaLinkage {
    /// Default CUDA toolkit paths (standard Linux/Windows install).
    pub fn default_paths() -> Self {
        Self {
            cudart: "libcudart".into(),
            libnvvm: "libnvvm".into(),
            nvcc: "nvcc".into(),
            libnvptx: "libnvptxcompiler_static".into(),
        }
    }

    /// Discover an actual CUDA toolkit layout from explicit overrides or standard install roots.
    pub fn discover() -> Option<Self> {
        explicit_cuda_linkage().or_else(|| discover_cuda_linkage_in_roots(cuda_install_roots()))
    }

    /// Return a discovered CUDA toolkit layout when available, or the generic linker names otherwise.
    pub fn resolved_or_default() -> Self {
        Self::discover().unwrap_or_else(Self::default_paths)
    }
}

fn env_path(name: &str) -> Option<PathBuf> {
    std::env::var(name)
        .ok()
        .map(PathBuf::from)
        .filter(|path| !path.as_os_str().is_empty())
}

fn path_string(path: &Path) -> String {
    path.to_string_lossy().into_owned()
}

fn push_unique_path(roots: &mut Vec<PathBuf>, seen: &mut BTreeSet<String>, path: PathBuf) {
    let rendered = path_string(&path);
    if seen.insert(rendered) {
        roots.push(path);
    }
}

fn explicit_cuda_linkage() -> Option<CudaLinkage> {
    let cudart = env_path(CUDA_CUDART_ENV)?;
    let libnvvm = env_path(CUDA_LIBNVVM_ENV)?;
    let nvcc = env_path(CUDA_NVCC_ENV)?;
    let libnvptx = env_path(CUDA_NVPTXCOMPILER_ENV)?;
    Some(CudaLinkage {
        cudart: path_string(&cudart),
        libnvvm: path_string(&libnvvm),
        nvcc: path_string(&nvcc),
        libnvptx: path_string(&libnvptx),
    })
}

fn cuda_install_roots() -> Vec<PathBuf> {
    let mut roots = Vec::new();
    let mut seen = BTreeSet::new();

    for env_name in [CUDA_ROOT_ENV, "CUDA_PATH", "CUDA_HOME", "CUDA_ROOT"] {
        if let Some(root) = env_path(env_name) {
            push_unique_path(&mut roots, &mut seen, root);
        }
    }

    if cfg!(windows) {
        for env_name in ["ProgramW6432", "ProgramFiles", "ProgramFiles(x86)"] {
            if let Some(base) = env_path(env_name) {
                let install_base = base.join("NVIDIA GPU Computing Toolkit").join("CUDA");
                let mut installs: Vec<PathBuf> = match std::fs::read_dir(&install_base) {
                    Ok(entries) => entries
                        .filter_map(Result::ok)
                        .map(|entry| entry.path())
                        .filter(|path| path.is_dir())
                        .collect(),
                    Err(_) => continue,
                };
                installs.sort_by(|left, right| {
                    right
                        .file_name()
                        .unwrap_or_default()
                        .to_string_lossy()
                        .cmp(&left.file_name().unwrap_or_default().to_string_lossy())
                });
                for root in installs {
                    push_unique_path(&mut roots, &mut seen, root);
                }
            }
        }
    } else {
        for root in ["/usr/local/cuda", "/opt/cuda"] {
            let candidate = PathBuf::from(root);
            if candidate.is_dir() {
                push_unique_path(&mut roots, &mut seen, candidate);
            }
        }
    }

    roots
}

fn find_first_existing_file<I>(candidates: I) -> Option<PathBuf>
where
    I: IntoIterator<Item = PathBuf>,
{
    candidates.into_iter().find(|path| path.is_file())
}

fn find_prefixed_file(dir: &Path, prefix: &str, suffix: &str) -> Option<PathBuf> {
    std::fs::read_dir(dir)
        .ok()?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .find(|path| {
            path.is_file()
                && path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| name.starts_with(prefix) && name.ends_with(suffix))
        })
}

fn cuda_linkage_from_root(root: &Path) -> Option<CudaLinkage> {
    let nvcc = find_first_existing_file([
        root.join("bin").join("nvcc.exe"),
        root.join("bin").join("nvcc"),
    ])?;

    let cudart = find_first_existing_file([
        root.join("lib").join("x64").join("cudart.lib"),
        root.join("lib64").join("libcudart.so"),
        root.join("targets")
            .join("x86_64-linux")
            .join("lib")
            .join("libcudart.so"),
    ])
    .or_else(|| find_prefixed_file(&root.join("bin"), "cudart64_", ".dll"))?;

    let libnvvm = find_first_existing_file([
        root.join("nvvm").join("lib").join("x64").join("nvvm.lib"),
        root.join("nvvm").join("lib64").join("libnvvm.so"),
        root.join("nvvm").join("bin").join("libnvvm.dll"),
        root.join("nvvm").join("bin").join("nvvm.dll"),
    ])
    .or_else(|| find_prefixed_file(&root.join("nvvm").join("bin"), "nvvm", ".dll"))?;

    let libnvptx = find_first_existing_file([
        root.join("lib")
            .join("x64")
            .join("nvptxcompiler_static.lib"),
        root.join("lib64").join("libnvptxcompiler_static.a"),
        root.join("targets")
            .join("x86_64-linux")
            .join("lib")
            .join("libnvptxcompiler_static.a"),
    ])
    .or_else(|| find_prefixed_file(&root.join("bin"), "nvptxcompiler", ".dll"))?;

    Some(CudaLinkage {
        cudart: path_string(&cudart),
        libnvvm: path_string(&libnvvm),
        nvcc: path_string(&nvcc),
        libnvptx: path_string(&libnvptx),
    })
}

fn discover_cuda_linkage_in_roots<I>(roots: I) -> Option<CudaLinkage>
where
    I: IntoIterator<Item = PathBuf>,
{
    roots
        .into_iter()
        .find_map(|root| cuda_linkage_from_root(&root))
}

fn emit_cuda_linkage_comment(out: &mut String, linkage: &CudaLinkage) {
    writeln!(out, "; cudart:  {}", linkage.cudart).unwrap();
    writeln!(out, "; libnvvm: {}", linkage.libnvvm).unwrap();
    writeln!(out, "; nvcc:    {}", linkage.nvcc).unwrap();
    writeln!(out, "; nvptx:   {}", linkage.libnvptx).unwrap();
    out.push('\n');
}

#[allow(dead_code)]
struct KernelLayout {
    param_types: Vec<String>,
    /// Per-param memory type annotations (None = default/unqualified).
    param_memory_types: Vec<Option<GpuMemoryType>>,
    /// Per-param restrict hints.
    param_restrict: Vec<bool>,
    value_types: HashMap<ValueId, &'static str>,
    local_types: HashMap<String, &'static str>,
}

fn kernel_ir_type_from_type_id(ty: agam_sema::symbol::TypeId) -> &'static str {
    match builtin_type_by_id(ty) {
        Some(Type::Bool) => "i1",
        Some(Type::Char) => "i32",
        Some(Type::Str) => "i8*",
        Some(Type::Unit) => "i32",
        Some(Type::Float(FloatSize::F32)) => "float",
        Some(Type::Float(FloatSize::F64)) => "double",
        Some(Type::Int(IntSize::I8)) | Some(Type::UInt(IntSize::I8)) => "i8",
        Some(Type::Int(IntSize::I16)) | Some(Type::UInt(IntSize::I16)) => "i16",
        Some(Type::Int(IntSize::I32)) | Some(Type::UInt(IntSize::I32)) => "i32",
        Some(Type::Int(IntSize::I64))
        | Some(Type::UInt(IntSize::I64))
        | Some(Type::Int(IntSize::ISize))
        | Some(Type::UInt(IntSize::ISize)) => "i64",
        Some(Type::Int(IntSize::I128)) | Some(Type::UInt(IntSize::I128)) => "i128",
        Some(Type::Int(IntSize::I256)) | Some(Type::UInt(IntSize::I256)) => "i256",
        Some(Type::Int(IntSize::I512)) | Some(Type::UInt(IntSize::I512)) => "i512",
        _ => "i8*",
    }
}

fn kernel_param_type(param: &MirParam) -> String {
    let base_ty: &str = match param.gpu_abi {
        GpuKernelParamAbi::OpaquePtr => kernel_ir_type_from_type_id(param.ty),
        abi => abi.llvm_ir(),
    };
    // If a memory type is set and this is a pointer param, qualify with address space
    if let Some(mem_type) = param.memory_type {
        if param.gpu_abi.is_pointer() {
            // Strip the trailing `*`, insert addrspace, re-add `*`
            if let Some(pointee) = base_ty.strip_suffix('*') {
                return format!("{}{}*", pointee.trim_end(), mem_type.llvm_addrspace_suffix());
            }
        }
    }
    base_ty.to_string()
}

fn can_skip_kernel_layout(func: &MirFunction) -> bool {
    func.params.is_empty()
        && func.blocks.iter().all(|block| {
            block.instructions.iter().all(|instr| {
                kernel_ir_type_from_type_id(instr.ty) == "i32"
                    && matches!(
                        instr.op,
                        Op::ConstInt(_)
                            | Op::BinOp { .. }
                            | Op::UnOp { .. }
                            | Op::Unit
                            | Op::GpuIntrinsic { .. }
                    )
            })
        })
}

fn analyze_kernel_layout(func: &MirFunction) -> KernelLayout {
    if can_skip_kernel_layout(func) {
        return KernelLayout {
            param_types: Vec::new(),
            param_memory_types: Vec::new(),
            param_restrict: Vec::new(),
            value_types: HashMap::new(),
            local_types: HashMap::new(),
        };
    }

    let mut layout = KernelLayout {
        param_types: func.params.iter().map(kernel_param_type).collect(),
        param_memory_types: func.params.iter().map(|p| p.memory_type).collect(),
        param_restrict: vec![false; func.params.len()],
        value_types: HashMap::new(),
        local_types: HashMap::new(),
    };

    for (index, param) in func.params.iter().enumerate() {
        let ty = layout.param_types.get(index).map(|s| s.as_str()).unwrap_or("i32");
        // Leak into 'static so existing code using &'static str works
        let ty_static: &'static str = Box::leak(ty.to_string().into_boxed_str());
        layout.value_types.insert(param.value, ty_static);
        layout.local_types.insert(param.name.clone(), ty_static);
    }

    for block in &func.blocks {
        for instr in &block.instructions {
            let inferred = match &instr.op {
                Op::Alloca { name, ty } => {
                    let local_ty = kernel_ir_type_from_type_id(*ty);
                    layout.local_types.insert(name.clone(), local_ty);
                    "i8*"
                }
                Op::StoreLocal { name, value } => {
                    let ty = layout
                        .value_types
                        .get(value)
                        .copied()
                        .unwrap_or_else(|| kernel_ir_type_from_type_id(instr.ty));
                    layout.local_types.insert(name.clone(), ty);
                    ty
                }
                Op::StoreIndex { value, .. } => layout
                    .value_types
                    .get(value)
                    .copied()
                    .unwrap_or_else(|| kernel_ir_type_from_type_id(instr.ty)),
                Op::GpuSharedAlloc { element_abi, .. } => element_abi.shared_ptr_llvm_ir(),
                Op::LoadLocal(name) => layout
                    .local_types
                    .get(name)
                    .copied()
                    .unwrap_or_else(|| kernel_ir_type_from_type_id(instr.ty)),
                Op::Copy(src) => layout
                    .value_types
                    .get(src)
                    .copied()
                    .unwrap_or_else(|| kernel_ir_type_from_type_id(instr.ty)),
                Op::GetIndex { object, .. } => layout
                    .value_types
                    .get(object)
                    .and_then(|ty| pointee_ir_type(ty))
                    .unwrap_or_else(|| kernel_ir_type_from_type_id(instr.ty)),
                _ => kernel_ir_type_from_type_id(instr.ty),
            };
            layout.value_types.insert(instr.result, inferred);
        }
    }

    layout
}

fn kernel_value_type<'a>(layout: &'a KernelLayout, value: ValueId) -> &'a str {
    layout.value_types.get(&value).copied().unwrap_or("i32")
}

fn kernel_local_type<'a>(layout: &'a KernelLayout, name: &str) -> &'a str {
    layout.local_types.get(name).copied().unwrap_or("i32")
}

fn is_float_ir(ty: &str) -> bool {
    matches!(ty, "float" | "double")
}

fn is_pointer_ir(ty: &str) -> bool {
    ty.ends_with('*')
}

fn pointee_ir_type(ty: &str) -> Option<&str> {
    let base = ty.strip_suffix('*')?.trim_end();
    // Strip any address space qualifier to get the pointee element type
    let stripped = base
        .strip_suffix(" addrspace(1)")
        .or_else(|| base.strip_suffix(" addrspace(3)"))
        .or_else(|| base.strip_suffix(" addrspace(4)"))
        .or_else(|| base.strip_suffix(" addrspace(5)"))
        .unwrap_or(base);
    Some(stripped)
}

fn default_value_for_ir(ty: &str) -> &'static str {
    match ty {
        "i1" => "false",
        "float" | "double" => "0.0",
        _ if is_pointer_ir(ty) => "null",
        _ => "0",
    }
}

fn emit_kernel_param_bindings(out: &mut String, func: &MirFunction, layout: &KernelLayout) {
    for (index, param) in func.params.iter().enumerate() {
        let ty = layout.param_types.get(index).map(|s| s.as_str()).unwrap_or("i32");
        // Emit memory type comment for qualified pointers
        if let Some(mem_type) = param.memory_type {
            write!(out, "  ; memory_type: {:?}\n", mem_type).unwrap();
        }
        out.push_str("  %local_");
        push_sanitized(out, &param.name);
        out.push_str(" = alloca ");
        out.push_str(ty);
        out.push('\n');
        write!(out, "  store {} %p{}, {}* %local_", ty, index, ty).unwrap();
        push_sanitized(out, &param.name);
        out.push('\n');
    }
}

/// Estimate output size in bytes for pre-allocation.
///
/// Each kernel function produces ~400 bytes of boilerplate + ~60 bytes/instruction.
/// Header + intrinsics are ~800 bytes. Over-estimate slightly to avoid realloc.
#[inline]
fn estimate_output_size(gpu_funcs: &[&MirFunction]) -> usize {
    let header_size = NVPTX_HEADER_PREFIX.len() + NVVM_INTRINSICS.len() + CUDA_FOOTER.len() + 512;
    let func_size: usize = gpu_funcs
        .iter()
        .map(|f| {
            let instr_count: usize = f.blocks.iter().map(|b| b.instructions.len()).sum();
            400 + instr_count * 64
        })
        .sum();
    header_size + func_size
}

/// Emit a GPU NVPTX64 LLVM IR module from `@gpu`-annotated functions.
///
/// Only functions with `gpu_config.is_some()` are included. Returns
/// `None` if no GPU kernels exist in the module.
pub fn emit_gpu_module(module: &MirModule) -> Option<String> {
    let gpu_funcs: Vec<&MirFunction> = module
        .functions
        .iter()
        .filter(|f| f.gpu_config.is_some())
        .collect();

    if gpu_funcs.is_empty() {
        return None;
    }

    // Pre-allocate output buffer based on estimated size
    let mut out = String::with_capacity(estimate_output_size(&gpu_funcs));

    // Header stays mostly static; linkage comments are rendered from discovered paths when available.
    out.push_str(NVPTX_HEADER_PREFIX);
    emit_cuda_linkage_comment(&mut out, &CudaLinkage::resolved_or_default());
    out.push_str(NVVM_INTRINSICS);

    // Kernel functions
    for func in &gpu_funcs {
        emit_kernel_function(&mut out, func);
    }

    // NVVM annotation metadata
    out.push_str("\n; ── NVVM Kernel Annotations ──\n");
    for (i, func) in gpu_funcs.iter().enumerate() {
        let mangled = mangle_kernel_name(&func.name);
        writeln!(
            out,
            "!{} = !{{void (...)* bitcast (void ()* @{} to void (...)*), !\"kernel\", i32 1}}",
            i, mangled
        )
        .unwrap();
    }
    write!(out, "!nvvm.annotations = !{{").unwrap();
    for (i, _) in gpu_funcs.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        write!(out, "!{}", i).unwrap();
    }
    out.push_str("}\n");

    // Static footer — single memcpy
    out.push('\n');
    out.push_str(CUDA_FOOTER);

    Some(out)
}

/// Emit a single kernel function in NVPTX calling convention.
fn emit_kernel_function(out: &mut String, func: &MirFunction) {
    let config = func.gpu_config.as_ref().unwrap();
    let mangled = mangle_kernel_name(&func.name);
    let layout = analyze_kernel_layout(func);

    // Config comment
    write!(
        out,
        "; @gpu(threads={}, shared={})\n",
        config.threads_per_block, config.shared_memory_bytes
    )
    .unwrap();

    // Function signature
    write!(out, "define ptx_kernel void @{}(", mangled).unwrap();
    for (i, param) in func.params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        let ty = layout.param_types.get(i).map(|s| s.as_str()).unwrap_or("i32");
        // Emit noalias for restrict-qualified params
        if param.memory_type.is_some() && param.gpu_abi.is_pointer() {
            write!(out, "{} noalias %p{}", ty, i).unwrap();
        } else {
            write!(out, "{} %p{}", ty, i).unwrap();
        }
    }
    out.push_str(") {\n");

    // Static preamble — single memcpy for thread index setup
    out.push_str(KERNEL_ENTRY_PREAMBLE);
    emit_kernel_param_bindings(out, func, &layout);

    // Emit kernel body — hot loop, optimized per-instruction
    for block in &func.blocks {
        if block.id != func.entry {
            write!(out, "block_{}:\n", block.id.0).unwrap();
        }
        for instr in &block.instructions {
            emit_kernel_instruction(out, &layout, instr);
        }
        emit_kernel_terminator(out, &block.terminator);
    }

    out.push_str("}\n\n");
}

/// Emit a single kernel instruction. Hot path — minimize allocations.
///
/// Uses direct `write!` to the output buffer instead of intermediate
/// `format!()` strings. The value name `%vN` is written inline.
#[inline]
fn emit_kernel_instruction(
    out: &mut String,
    layout: &KernelLayout,
    instr: &agam_mir::ir::Instruction,
) {
    let id = instr.result.0;
    let result_ty = kernel_value_type(layout, instr.result);
    match &instr.op {
        Op::ConstInt(val) => {
            write!(out, "  %v{} = add {} 0, {}\n", id, result_ty, val).unwrap();
        }
        Op::ConstFloat(val) => {
            write!(out, "  %v{} = fadd {} 0.0, {:.6}\n", id, result_ty, val).unwrap();
        }
        Op::ConstBool(val) => {
            write!(out, "  %v{} = add i1 0, {}\n", id, if *val { 1 } else { 0 }).unwrap();
        }
        Op::BinOp { op, left, right } => {
            let operand_ty = kernel_value_type(layout, *left);
            let opcode = binop_opcode(*op, operand_ty);
            write!(
                out,
                "  %v{} = {} {} %v{}, %v{}\n",
                id, opcode, operand_ty, left.0, right.0
            )
            .unwrap();
        }
        Op::UnOp { op, operand } => {
            let operand_ty = kernel_value_type(layout, *operand);
            match op {
                MirUnOp::Neg if is_float_ir(operand_ty) => write!(
                    out,
                    "  %v{} = fsub {} 0.0, %v{}\n",
                    id, operand_ty, operand.0
                )
                .unwrap(),
                MirUnOp::Neg => {
                    write!(out, "  %v{} = sub {} 0, %v{}\n", id, operand_ty, operand.0).unwrap()
                }
                MirUnOp::Not => write!(out, "  %v{} = xor i1 %v{}, true\n", id, operand.0).unwrap(),
                MirUnOp::BitNot => {
                    write!(out, "  %v{} = xor {} %v{}, -1\n", id, operand_ty, operand.0).unwrap()
                }
            }
        }
        Op::Copy(src) => {
            let ty = kernel_value_type(layout, *src);
            write!(
                out,
                "  %v{} = select i1 true, {} %v{}, {} {}\n",
                id,
                ty,
                src.0,
                ty,
                default_value_for_ir(ty)
            )
            .unwrap();
        }
        Op::Unit => {
            write!(out, "  ; %v{} = unit (void)\n", id).unwrap();
        }
        Op::LoadLocal(name) => {
            let ty = kernel_local_type(layout, name);
            write!(out, "  %v{} = load {}, {}* %local_", id, ty, ty).unwrap();
            push_sanitized(out, name);
            out.push('\n');
        }
        Op::StoreLocal { name, value } => {
            let ty = kernel_local_type(layout, name);
            write!(out, "  store {} %v{}, {}* %local_", ty, value.0, ty).unwrap();
            push_sanitized(out, name);
            out.push('\n');
        }
        Op::StoreIndex {
            object,
            index,
            value,
        } => {
            let object_ty = kernel_value_type(layout, *object);
            let value_ty = kernel_value_type(layout, *value);
            if let Some(element_ty) = pointee_ir_type(object_ty) {
                write!(
                    out,
                    "  %v{}.ptr = getelementptr inbounds {}, {} %v{}, i32 %v{}\n",
                    id, element_ty, object_ty, object.0, index.0
                )
                .unwrap();
                write!(
                    out,
                    "  store {} %v{}, {} %v{}.ptr\n",
                    element_ty, value.0, object_ty, id
                )
                .unwrap();
                write!(
                    out,
                    "  %v{} = select i1 true, {} %v{}, {} {}\n",
                    id,
                    value_ty,
                    value.0,
                    value_ty,
                    default_value_for_ir(value_ty)
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "  ; ERROR: cannot index-store into non-pointer GPU value of type {}",
                    object_ty
                )
                .unwrap();
                write!(
                    out,
                    "  %v{} = select i1 true, {} %v{}, {} {}\n",
                    id,
                    value_ty,
                    value.0,
                    value_ty,
                    default_value_for_ir(value_ty)
                )
                .unwrap();
            }
        }
        Op::Alloca { name, .. } => {
            let ty = kernel_local_type(layout, name);
            out.push_str("  %local_");
            push_sanitized(out, name);
            out.push_str(" = alloca ");
            out.push_str(ty);
            out.push('\n');
        }
        Op::GpuSharedAlloc { element_abi, count } => {
            write!(
                out,
                "  %v{} = alloca {}, i32 %v{}, addrspace(3)\n",
                id,
                element_abi.pointee_llvm_ir(),
                count.0
            )
            .unwrap();
        }
        Op::ConstString(_) => {
            out.push_str("  ; ERROR: string operations not allowed in GPU kernels\n");
        }
        Op::EffectPerform { .. } | Op::HandleWith { .. } => {
            out.push_str("  ; ERROR: effects not allowed in GPU kernels\n");
        }
        Op::GpuKernelLaunch { .. } => {
            out.push_str("  ; ERROR: nested kernel launch not allowed\n");
        }
        Op::GpuIntrinsic { kind, args } => {
            emit_gpu_intrinsic(out, id, *kind, args);
        }
        Op::InlineAsm {
            asm_string,
            constraints,
            args,
        } => {
            // Inline PTX assembly — emit as LLVM inline asm
            let arg_strs: Vec<String> = args
                .iter()
                .map(|a| format!("{} %v{}", kernel_value_type(layout, *a), a.0))
                .collect();
            write!(
                out,
                "  %v{} = call {} asm sideeffect \"{}\", \"{}\"({})\n",
                id,
                result_ty,
                asm_string,
                constraints,
                arg_strs.join(", ")
            )
            .unwrap();
        }
        Op::Call { callee, args } => {
            let arg_strs: Vec<String> = args
                .iter()
                .map(|a| format!("{} %v{}", kernel_value_type(layout, *a), a.0))
                .collect();
            write!(
                out,
                "  %v{} = call {} @{}({})\n",
                id,
                result_ty,
                callee,
                arg_strs.join(", ")
            )
            .unwrap();
        }
        Op::GetIndex { object, index } => {
            let object_ty = kernel_value_type(layout, *object);
            if let Some(element_ty) = pointee_ir_type(object_ty) {
                write!(
                    out,
                    "  %v{}.ptr = getelementptr inbounds {}, {} %v{}, i32 %v{}\n",
                    id, element_ty, object_ty, object.0, index.0
                )
                .unwrap();
                write!(
                    out,
                    "  %v{} = load {}, {} %v{}.ptr\n",
                    id, element_ty, object_ty, id
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "  ; ERROR: cannot index non-pointer GPU value of type {}",
                    object_ty
                )
                .unwrap();
                write!(
                    out,
                    "  %v{} = select i1 true, {} {}, {} {}\n",
                    id,
                    result_ty,
                    default_value_for_ir(result_ty),
                    result_ty,
                    default_value_for_ir(result_ty)
                )
                .unwrap();
            }
        }
        Op::GetField { .. }
        | Op::Phi(_)
        | Op::Cast { .. }
        | Op::EnumConstruct { .. }
        | Op::EnumTag(_)
        | Op::EnumPayload { .. } => {
            write!(out, "  ; unhandled GPU op: {:?}\n", instr.op).unwrap();
        }
    }
}

/// BinOp → LLVM opcode lookup. Returns static &str (zero allocation).
#[inline]
fn binop_opcode(op: MirBinOp, operand_ty: &str) -> &'static str {
    if is_float_ir(operand_ty) {
        match op {
            MirBinOp::Add => "fadd",
            MirBinOp::Sub => "fsub",
            MirBinOp::Mul => "fmul",
            MirBinOp::Div => "fdiv",
            MirBinOp::Mod => "frem",
            MirBinOp::Eq => "fcmp oeq",
            MirBinOp::NotEq => "fcmp one",
            MirBinOp::Lt => "fcmp olt",
            MirBinOp::LtEq => "fcmp ole",
            MirBinOp::Gt => "fcmp ogt",
            MirBinOp::GtEq => "fcmp oge",
            MirBinOp::And => "and",
            MirBinOp::Or => "or",
            MirBinOp::BitAnd => "and",
            MirBinOp::BitOr => "or",
            MirBinOp::BitXor => "xor",
            MirBinOp::Shl => "shl",
            MirBinOp::Shr => "ashr",
        }
    } else {
        match op {
            MirBinOp::Add => "add",
            MirBinOp::Sub => "sub",
            MirBinOp::Mul => "mul",
            MirBinOp::Div => "sdiv",
            MirBinOp::Mod => "srem",
            MirBinOp::Eq => "icmp eq",
            MirBinOp::NotEq => "icmp ne",
            MirBinOp::Lt => "icmp slt",
            MirBinOp::LtEq => "icmp sle",
            MirBinOp::Gt => "icmp sgt",
            MirBinOp::GtEq => "icmp sge",
            MirBinOp::And => "and",
            MirBinOp::Or => "or",
            MirBinOp::BitAnd => "and",
            MirBinOp::BitOr => "or",
            MirBinOp::BitXor => "xor",
            MirBinOp::Shl => "shl",
            MirBinOp::Shr => "ashr",
        }
    }
}

/// Emit a kernel block terminator.
#[inline]
fn emit_kernel_terminator(out: &mut String, term: &Terminator) {
    match term {
        Terminator::Return(_) | Terminator::ReturnVoid => {
            out.push_str("  ret void\n");
        }
        Terminator::Jump(target) => {
            write!(out, "  br label %block_{}\n", target.0).unwrap();
        }
        Terminator::Branch {
            condition,
            then_block,
            else_block,
        } => {
            write!(
                out,
                "  br i1 %v{}, label %block_{}, label %block_{}\n",
                condition.0, then_block.0, else_block.0
            )
            .unwrap();
        }
        Terminator::Unreachable | Terminator::Switch { .. } => {
            out.push_str("  unreachable\n");
        }
    }
}

/// Mangle a kernel name for NVPTX. Avoids allocation when name is already clean.
fn mangle_kernel_name(name: &str) -> String {
    let mut out = String::with_capacity(12 + name.len());
    out.push_str("__agam_gpu_");
    for c in name.chars() {
        if c.is_alphanumeric() {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    out
}

/// Emit LLVM NVVM intrinsic calls for GPU intrinsics.
#[inline]
fn emit_gpu_intrinsic(
    out: &mut String,
    id: u32,
    kind: GpuIntrinsicKind,
    args: &[agam_mir::ir::ValueId],
) {
    match kind {
        GpuIntrinsicKind::ThreadIdX => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::ThreadIdY => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.tid.y()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::ThreadIdZ => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.tid.z()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::BlockDimX => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::BlockDimY => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.ntid.y()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::BlockDimZ => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.ntid.z()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::BlockIdX => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::BlockIdY => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.y()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::BlockIdZ => write!(
            out,
            "  %v{} = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.z()\n",
            id
        )
        .unwrap(),
        GpuIntrinsicKind::Barrier => {
            write!(out, "  call void @llvm.nvvm.barrier0()\n").unwrap();
            write!(out, "  %v{} = add i32 0, 0\n", id).unwrap(); // dummy result
        }
        GpuIntrinsicKind::WarpShuffleDown => {
            if args.len() == 4 {
                write!(out, "  %v{} = call i32 @llvm.nvvm.shfl.sync.down.i32(i32 %v{}, i32 %v{}, i32 %v{}, i32 %v{})\n", 
                    id, args[0].0, args[1].0, args[2].0, args[3].0).unwrap();
            } else {
                write!(out, "  ; ERROR: WarpShuffleDown needs 4 args\n").unwrap();
            }
        }
        GpuIntrinsicKind::WarpReduceAdd => {
            // Simplified fallback if it's an intrinsic directly mapped, though real NVPTX requires a loop
            write!(out, "  ; WARN: WarpReduceAdd mapped to stub\n").unwrap();
            write!(out, "  %v{} = add i32 0, 0\n", id).unwrap();
        }
        GpuIntrinsicKind::BallotSync => {
            if args.len() == 2 {
                write!(
                    out,
                    "  %v{} = call i32 @llvm.nvvm.vote.ballot.sync(i32 %v{}, i1 %v{})\n",
                    id, args[0].0, args[1].0
                )
                .unwrap();
            } else {
                write!(out, "  ; ERROR: BallotSync needs 2 args\n").unwrap();
            }
        }
        GpuIntrinsicKind::NvvmSin => write!(
            out,
            "  %v{} = call float @llvm.nvvm.sin.approx.f(float %v{})\n",
            id, args[0].0
        )
        .unwrap(),
        GpuIntrinsicKind::NvvmCos => write!(
            out,
            "  %v{} = call float @llvm.nvvm.cos.approx.f(float %v{})\n",
            id, args[0].0
        )
        .unwrap(),
        GpuIntrinsicKind::NvvmSqrt => write!(
            out,
            "  %v{} = call float @llvm.nvvm.sqrt.approx.f(float %v{})\n",
            id, args[0].0
        )
        .unwrap(),
        GpuIntrinsicKind::NvvmExp => write!(
            out,
            "  %v{} = call float @llvm.nvvm.ex2.approx.f(float %v{})\n",
            id, args[0].0
        )
        .unwrap(),
    }
}

/// Push sanitized name directly into buffer (avoids intermediate String).
#[inline]
fn push_sanitized(out: &mut String, name: &str) {
    for c in name.chars() {
        if c.is_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
}

/// Generate the host-side CUDA runtime launch stub for linking.
pub fn emit_host_cuda_declarations() -> String {
    HOST_CUDA_DECLS.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use agam_errors::span::SourceId;
    use agam_hir::lower::HirLowering;
    use agam_lexer::{Lexer, TokenKind};
    use agam_mir::ir::*;
    use agam_mir::lower::MirLowering;
    use agam_parser::Parser;
    use agam_sema::gpu::GpuKernelConfig;
    use agam_sema::target::TargetProfile;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn make_gpu_module(funcs: Vec<MirFunction>) -> MirModule {
        MirModule {
            functions: funcs,
            enum_layouts: HashMap::new(),
            struct_layouts: HashMap::new(),
        }
    }

    fn make_gpu_function(name: &str, threads: u32) -> MirFunction {
        MirFunction {
            name: name.into(),
            generics: vec![],
            params: vec![],
            return_ty: agam_sema::symbol::TypeId(0),
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![Instruction {
                    result: ValueId(0),
                    ty: agam_sema::symbol::TypeId(0),
                    op: Op::ConstInt(42),
                }],
                terminator: Terminator::ReturnVoid,
            }],
            entry: BlockId(0),
            target: TargetProfile::Default,
            gpu_config: Some(GpuKernelConfig {
                threads_per_block: threads,
                shared_memory_bytes: 0,
                grid_dim: None,
            }),
        }
    }

    /// Build a heavier kernel with N instructions for throughput testing.
    fn make_heavy_kernel(name: &str, instr_count: usize) -> MirFunction {
        let mut instructions = Vec::with_capacity(instr_count);
        for i in 0..instr_count {
            let op = if i == 0 {
                Op::ConstInt(i as i64)
            } else {
                Op::BinOp {
                    op: MirBinOp::Add,
                    left: ValueId((i - 1) as u32),
                    right: ValueId(0),
                }
            };
            instructions.push(Instruction {
                result: ValueId(i as u32),
                ty: agam_sema::symbol::TypeId(0),
                op,
            });
        }
        MirFunction {
            name: name.into(),
            generics: vec![],
            params: vec![],
            return_ty: agam_sema::symbol::TypeId(0),
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions,
                terminator: Terminator::ReturnVoid,
            }],
            entry: BlockId(0),
            target: TargetProfile::Default,
            gpu_config: Some(GpuKernelConfig {
                threads_per_block: 256,
                shared_memory_bytes: 0,
                grid_dim: None,
            }),
        }
    }

    fn unique_temp_dir(label: &str) -> PathBuf {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock before unix epoch")
            .as_nanos();
        let dir = std::env::temp_dir().join(format!(
            "agam_cuda_linkage_{label}_{}_{}",
            std::process::id(),
            stamp
        ));
        std::fs::create_dir_all(&dir).expect("create temp dir");
        dir
    }

    fn touch(path: &Path) {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("create parent directory");
        }
        std::fs::write(path, b"").expect("create file");
    }

    fn emit_gpu_ir_from_source(source: &str) -> String {
        let source_id = SourceId(0);
        let mut lexer = Lexer::new(source, source_id);
        let mut tokens = Vec::new();
        loop {
            let tok = lexer.next_token();
            let is_eof = tok.kind == TokenKind::Eof;
            tokens.push(tok);
            if is_eof {
                break;
            }
        }

        let mut parser = Parser::new(tokens);
        let module = parser.parse_module(source_id).expect("parse failed");
        let mut hir_lowering = HirLowering::new();
        let hir = hir_lowering.lower_module(&module);
        assert!(
            hir_lowering.diagnostics.is_empty(),
            "unexpected HIR diagnostics: {:?}",
            hir_lowering.diagnostics
        );

        let mut mir_lowering = MirLowering::new();
        let mir = mir_lowering.lower_module(&hir);
        emit_gpu_module(&mir).expect("expected gpu module")
    }

    #[test]
    fn no_gpu_functions_returns_none() {
        let module = MirModule {
            functions: vec![MirFunction {
                name: "main".into(),
                generics: vec![],
                params: vec![],
                return_ty: agam_sema::symbol::TypeId(0),
                blocks: vec![],
                entry: BlockId(0),
                target: TargetProfile::Default,
                gpu_config: None,
            }],
            enum_layouts: HashMap::new(),
            struct_layouts: HashMap::new(),
        };
        assert!(emit_gpu_module(&module).is_none());
    }

    #[test]
    fn emits_nvptx64_target_triple() {
        let module = make_gpu_module(vec![make_gpu_function("kern", 256)]);
        let ir = emit_gpu_module(&module).unwrap();
        assert!(ir.contains("nvptx64-nvidia-cuda"));
    }

    #[test]
    fn emits_thread_intrinsic_declarations() {
        let module = make_gpu_module(vec![make_gpu_function("kern", 256)]);
        let ir = emit_gpu_module(&module).unwrap();
        assert!(ir.contains("@llvm.nvvm.read.ptx.sreg.tid.x"));
        assert!(ir.contains("@llvm.nvvm.read.ptx.sreg.ctaid.x"));
        assert!(ir.contains("@llvm.nvvm.read.ptx.sreg.ntid.x"));
    }

    #[test]
    fn emits_ptx_kernel_calling_convention() {
        let module = make_gpu_module(vec![make_gpu_function("kern", 512)]);
        let ir = emit_gpu_module(&module).unwrap();
        assert!(ir.contains("define ptx_kernel void @__agam_gpu_kern"));
    }

    #[test]
    fn emits_nvvm_annotations() {
        let module = make_gpu_module(vec![make_gpu_function("kern", 256)]);
        let ir = emit_gpu_module(&module).unwrap();
        assert!(ir.contains("!nvvm.annotations"));
        assert!(ir.contains("\"kernel\""));
    }

    #[test]
    fn emits_cuda_library_references() {
        let module = make_gpu_module(vec![make_gpu_function("kern", 256)]);
        let ir = emit_gpu_module(&module).unwrap();
        assert!(ir.contains("cudart"));
        assert!(ir.contains("nvvm"));
        assert!(ir.contains("nvptxcompiler"));
    }

    #[test]
    fn discovers_cuda_linkage_from_windows_style_root() {
        let root = unique_temp_dir("windows_root");
        let nvcc = root.join("bin").join("nvcc.exe");
        let cudart = root.join("lib").join("x64").join("cudart.lib");
        let libnvvm = root.join("nvvm").join("lib").join("x64").join("nvvm.lib");
        let libnvptx = root
            .join("lib")
            .join("x64")
            .join("nvptxcompiler_static.lib");
        touch(&nvcc);
        touch(&cudart);
        touch(&libnvvm);
        touch(&libnvptx);

        let linkage = discover_cuda_linkage_in_roots([root.clone()]).expect("discover linkage");
        assert_eq!(linkage.nvcc, path_string(&nvcc));
        assert_eq!(linkage.cudart, path_string(&cudart));
        assert_eq!(linkage.libnvvm, path_string(&libnvvm));
        assert_eq!(linkage.libnvptx, path_string(&libnvptx));

        std::fs::remove_dir_all(root).expect("remove temp dir");
    }

    #[test]
    fn discovers_cuda_linkage_with_windows_dll_fallbacks() {
        let root = unique_temp_dir("windows_dlls");
        let nvcc = root.join("bin").join("nvcc.exe");
        let cudart = root.join("bin").join("cudart64_130.dll");
        let libnvvm = root.join("nvvm").join("bin").join("nvvm64_40_0.dll");
        let libnvptx = root.join("bin").join("nvptxcompiler64_130_0.dll");
        touch(&nvcc);
        touch(&cudart);
        touch(&libnvvm);
        touch(&libnvptx);

        let linkage = discover_cuda_linkage_in_roots([root.clone()]).expect("discover linkage");
        assert_eq!(linkage.nvcc, path_string(&nvcc));
        assert_eq!(linkage.cudart, path_string(&cudart));
        assert_eq!(linkage.libnvvm, path_string(&libnvvm));
        assert_eq!(linkage.libnvptx, path_string(&libnvptx));

        std::fs::remove_dir_all(root).expect("remove temp dir");
    }

    #[test]
    fn rendered_cuda_linkage_comment_uses_discovered_paths() {
        let mut out = String::new();
        emit_cuda_linkage_comment(
            &mut out,
            &CudaLinkage {
                cudart: "C:/cuda/lib/x64/cudart.lib".into(),
                libnvvm: "C:/cuda/nvvm/lib/x64/nvvm.lib".into(),
                nvcc: "C:/cuda/bin/nvcc.exe".into(),
                libnvptx: "C:/cuda/lib/x64/nvptxcompiler_static.lib".into(),
            },
        );
        assert!(out.contains("C:/cuda/lib/x64/cudart.lib"));
        assert!(out.contains("C:/cuda/nvvm/lib/x64/nvvm.lib"));
        assert!(out.contains("C:/cuda/bin/nvcc.exe"));
        assert!(out.contains("C:/cuda/lib/x64/nvptxcompiler_static.lib"));
    }

    #[test]
    fn lowers_gpu_buffer_and_scalar_params_from_source() {
        let ir = emit_gpu_ir_from_source(
            "@gpu\nfn kern(input: [f32], output: *mut i32, scale: f32): let root = agam.gpu.sqrt(scale)",
        );
        assert!(
            ir.contains("define ptx_kernel void @__agam_gpu_kern(float* %p0, i32* %p1, float %p2)")
        );
        assert!(ir.contains("store float* %p0, float** %local_input"));
        assert!(ir.contains("store i32* %p1, i32** %local_output"));
        assert!(ir.contains("store float %p2, float* %local_scale"));
        assert!(ir.contains("load float, float* %local_scale"));
        assert!(ir.contains("@llvm.nvvm.sqrt.approx.f(float"));
    }

    #[test]
    fn lowers_fixed_array_gpu_params_as_pointers_from_source() {
        let ir = emit_gpu_ir_from_source(
            "@gpu\nfn kern(input: [f32; 64], output: *mut f32) { let tid = agam.gpu.thread_id_x(); output[tid] = input[tid]; }",
        );
        assert!(ir.contains("define ptx_kernel void @__agam_gpu_kern(float* %p0, float* %p1)"));
        assert!(ir.contains("store float* %p0, float** %local_input"));
        assert!(ir.contains("getelementptr inbounds float, float*"));
        assert!(!ir.contains("unhandled GPU op: GetIndex"));
        assert!(!ir.contains("unhandled GPU op: StoreIndex"));
    }

    #[test]
    fn lowers_wide_integer_gpu_params_from_source() {
        let ir = emit_gpu_ir_from_source("@gpu\nfn kern(a: i256, b: *mut u512): return 0");
        assert!(ir.contains("define ptx_kernel void @__agam_gpu_kern(i256 %p0, i512* %p1)"));
        assert!(ir.contains("store i256 %p0, i256* %local_a"));
        assert!(ir.contains("store i512* %p1, i512** %local_b"));
    }

    #[test]
    fn lowers_gpu_indexed_buffer_reads_and_writes() {
        let ir = emit_gpu_ir_from_source(
            "@gpu\nfn kern(input: [f32], output: *mut f32) { let tid = agam.gpu.thread_id_x(); output[tid] = input[tid]; }",
        );
        assert!(ir.contains("getelementptr inbounds float, float*"));
        assert!(ir.contains("load float, float* %v"));
        assert!(ir.contains("store float %v"));
        assert!(!ir.contains("unhandled GPU op: GetIndex"));
        assert!(!ir.contains("unhandled GPU op: StoreIndex"));
    }

    #[test]
    fn lowers_gpu_shared_alloc_to_addrspace3_memory() {
        let ir = emit_gpu_ir_from_source(
            "@gpu\nfn kern(): let scratch: *mut f32 = agam.gpu.shared_alloc(128)",
        );
        assert!(ir.contains("alloca float, i32 %v"));
        assert!(ir.contains("addrspace(3)"));
    }

    #[test]
    fn lowers_fixed_array_shared_alloc_to_addrspace3_memory() {
        let ir = emit_gpu_ir_from_source(
            "@gpu\nfn kern(): let scratch: [i32; 128] = agam.gpu.shared_alloc(128)",
        );
        assert!(ir.contains("alloca i32, i32 %v"));
        assert!(ir.contains("addrspace(3)"));
    }

    #[test]
    fn lowers_wide_integer_shared_alloc_to_addrspace3_memory() {
        let ir = emit_gpu_ir_from_source(
            "@gpu\nfn kern(): let scratch: [u256; 32] = agam.gpu.shared_alloc(32)",
        );
        assert!(ir.contains("alloca i256, i32 %v"));
        assert!(ir.contains("addrspace(3)"));
    }

    #[test]
    fn emits_barrier_intrinsic() {
        let module = make_gpu_module(vec![make_gpu_function("kern", 256)]);
        let ir = emit_gpu_module(&module).unwrap();
        assert!(ir.contains("@llvm.nvvm.barrier0"));
    }

    #[test]
    fn host_cuda_declarations_contain_runtime_api() {
        let decls = emit_host_cuda_declarations();
        assert!(decls.contains("cudaLaunchKernel"));
        assert!(decls.contains("cudaMalloc"));
        assert!(decls.contains("cudaFree"));
        assert!(decls.contains("cudaMemcpy"));
        assert!(decls.contains("cudaDeviceSynchronize"));
        assert!(decls.contains("-lcudart"));
        assert!(decls.contains("-lnvvm"));
    }

    #[test]
    fn threads_config_appears_in_comment() {
        let module = make_gpu_module(vec![make_gpu_function("kern", 1024)]);
        let ir = emit_gpu_module(&module).unwrap();
        assert!(ir.contains("threads=1024"));
    }

    // ── Throughput benchmarks ──

    #[test]
    fn benchmark_single_kernel_1k_instructions() {
        let module = make_gpu_module(vec![make_heavy_kernel("bench", 1000)]);
        let start = std::time::Instant::now();
        let iterations = 1000;
        let mut total_bytes = 0usize;
        for _ in 0..iterations {
            let ir = emit_gpu_module(&module).unwrap();
            total_bytes += ir.len();
            std::hint::black_box(&ir);
        }
        let elapsed = start.elapsed();
        let us_per_iter = elapsed.as_micros() as f64 / iterations as f64;
        let mb_per_sec = (total_bytes as f64 / elapsed.as_secs_f64()) / 1_000_000.0;
        eprintln!(
            "[GPU bench] 1 kernel × 1000 instrs × {} iters: {:.1} µs/iter, {:.0} MB/s",
            iterations, us_per_iter, mb_per_sec
        );
        // Agam target: < 100µs per kernel (1000 instrs)
        // Python/nvcc baseline: ~50,000µs (50ms) subprocess launch alone
        assert!(
            us_per_iter < 5000.0,
            "GPU IR gen too slow: {:.1} µs",
            us_per_iter
        );
    }

    #[test]
    fn benchmark_batch_100_kernels() {
        let funcs: Vec<MirFunction> = (0..100)
            .map(|i| make_heavy_kernel(&format!("kern_{}", i), 200))
            .collect();
        let module = make_gpu_module(funcs);
        let start = std::time::Instant::now();
        let iterations = 100;
        let mut total_bytes = 0usize;
        for _ in 0..iterations {
            let ir = emit_gpu_module(&module).unwrap();
            total_bytes += ir.len();
            std::hint::black_box(&ir);
        }
        let elapsed = start.elapsed();
        let us_per_iter = elapsed.as_micros() as f64 / iterations as f64;
        let mb_per_sec = (total_bytes as f64 / elapsed.as_secs_f64()) / 1_000_000.0;
        eprintln!(
            "[GPU bench] 100 kernels × 200 instrs × {} iters: {:.1} µs/iter, {:.0} MB/s",
            iterations, us_per_iter, mb_per_sec
        );
        // 100 kernels should still be < 10ms total
        assert!(
            us_per_iter < 50_000.0,
            "Batch GPU IR gen too slow: {:.1} µs",
            us_per_iter
        );
    }

    #[test]
    fn benchmark_prealloc_accuracy() {
        let module = make_gpu_module(vec![make_heavy_kernel("bench", 500)]);
        let ir = emit_gpu_module(&module).unwrap();
        let gpu_funcs: Vec<&MirFunction> = module
            .functions
            .iter()
            .filter(|f| f.gpu_config.is_some())
            .collect();
        let estimated = estimate_output_size(&gpu_funcs);
        let actual = ir.len();
        let ratio = estimated as f64 / actual as f64;
        eprintln!(
            "[GPU bench] Pre-alloc: estimated={}, actual={}, ratio={:.2}x",
            estimated, actual, ratio
        );
        // Estimate should be within 0.5x–3.0x of actual (no wild over/under)
        assert!(
            ratio > 0.5 && ratio < 3.0,
            "Pre-alloc estimate off: {:.2}x (est={}, actual={})",
            ratio,
            estimated,
            actual
        );
    }
}
