//! Stackless Coroutine & State Machine Representation.
//!
//! Provides the foundational execution engine for lowered `async fn` state machines,
//! generators, and resumable continuations without requiring stack allocation.

use std::fmt;
use std::pin::Pin;

/// State of a stackless coroutine after execution of a single step.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CoroutineState<Y, R> {
    /// The coroutine suspended at a yield point, producing a yield value.
    Yielded(Y),
    /// The coroutine reached its terminal return point, producing a final result.
    Complete(R),
}

/// A stackless coroutine that can be resumed with input arguments and produces
/// either an intermediate yield value or a final return value.
pub trait Coroutine<Input = ()> {
    type Yield;
    type Return;

    /// Resume the execution of the coroutine from its current state transition.
    fn resume(self: Pin<&mut Self>, input: Input) -> CoroutineState<Self::Yield, Self::Return>;
}

/// Generic Generator wrapper transforming a coroutine into an iterator over yielded items.
pub struct Generator<C> {
    coroutine: C,
    is_done: bool,
}

impl<C> Generator<C> {
    pub fn new(coroutine: C) -> Self {
        Self {
            coroutine,
            is_done: false,
        }
    }

    pub fn is_done(&self) -> bool {
        self.is_done
    }
}

impl<C> Iterator for Generator<C>
where
    C: Coroutine<(), Return = ()> + Unpin,
{
    type Item = C::Yield;

    fn next(&mut self) -> Option<Self::Item> {
        if self.is_done {
            return None;
        }

        let pin = Pin::new(&mut self.coroutine);
        match pin.resume(()) {
            CoroutineState::Yielded(val) => Some(val),
            CoroutineState::Complete(()) => {
                self.is_done = true;
                None
            }
        }
    }
}

/// State tracking for discrete state machines generated by HIR/MIR coroutine lowering.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct StateTag(pub u32);

impl StateTag {
    pub const INIT: Self = Self(0);
    pub const COMPLETE: Self = Self(u32::MAX);

    pub fn next(self) -> Self {
        Self(self.0.saturating_add(1))
    }
}

impl fmt::Display for StateTag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            0 => write!(f, "State::Init"),
            u32::MAX => write!(f, "State::Complete"),
            n => write!(f, "State({n})"),
        }
    }
}
